### ISSUE TITLE
Wrong class in the SpringApplication.run method

### ISSUE THREAD

**Issue by deepres** [spring-guides/gs-spring-boot-docker#12]
I hope I understood your guide correctly and there should be:

    public static void main(String[] args) {
        SpringApplication.run(WeatherConfiguration.class);
    }

instead of Application.class

**Comment by dsyer** [comment]
I don't see any `WeatherConfiguration` in this project. Where did that come from?

**Comment by dsyer** [comment]
Wrong project.
