### ISSUE TITLE
Change the Dockerfile RUN bash to RUN sh

### ISSUE THREAD

**Issue by rjain-pivotal** [spring-guides/gs-spring-boot-docker#16]
FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD gs-spring-boot-docker-0.1.0.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

The alpine oracle Docker image doesn't have bash
Change the RUN command 
RUN sh -c 'touch /app.jar'

**Comment by dsyer** [comment]
Ouch, good catch . I should have spotted that.

**Comment by willis7** [comment]
This caught me out too, an update on the guide may help others
