### ISSUE TITLE
push

### ISSUE THREAD

**Issue by eugenetaranov** [spring-guides/gs-spring-boot-docker#17]
Hello,

can you please provide some more details on push. Doc states 
> The "docker push" will fail for you (unless you are part of the "springio" organization at Dockerhub), but if you change the configuration to match your own docker ID then it should succeed, and you will have a new tagged, deployed image

Would you mind providing an example how it should be configured to avoid push error at the end of the building process ?

Thank you.

**Comment by gregturn** [comment]
Register on docker hub and plugin your user ID.
