### ISSUE TITLE
If targetPath is set to / on windows, docker:build fails.

### ISSUE THREAD

**Issue by kalvarez2** [spring-guides/gs-spring-boot-docker#18]
Just removing the relativePath line from the pom fixes the problem, not sure why it does that.

Command:
mvn clean package docker:build

Error displayed on  is:
 [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.3:build (default-cli) on project gs-spring-boot-docker: Exception caught: UNC path is missing
 sharename: /\gs-spring-boot-docker-0.1.0.jar -> [Help 1]

**Comment by joedoehh** [comment]
encountered same problem on windows using docker-maven-plugin in version 0.2.3, removing 

<targetPath>/</targetPath>

from my resource definition of plugin configuration worked

**Comment by dsyer** [comment]
This issue seems redundant now (we are not using that plugin any more). Maybe open another one if there is still a problem with more up to date details?
