### ISSUE TITLE
Guide does not mention default docker tag

### ISSUE THREAD

**Issue by a-p-o** [spring-guides/gs-spring-boot-docker#19]
I spent a while trying to find out why I was getting this message:

```
Unable to find image 'com.group/application:latest' locally
docker: Error response from daemon: Get https://com.group/v1/_ping: dial tcp: lookup com.group on 10.0.2.3:53: no such host.
See 'docker run --help'.
```

after running `docker run -p 8080:8080 -t com.group/application`.

I found that the Docker plugin for Gradle takes the `version` and uses that as the Docker tag.

So instead of using `latest` as the tag like the command above assumes, I had `1.0-SNAPSHOT`.

I think  `tagVersion = 'latest'` should be specified in the `buildDocker` task to be more consistent with the rest of the guide.

**Comment by miguelsauza** [comment]
Set 'version' property is enough.

> tagVersion - Optional version name added to the image tag name. Defaults to project.version or "latest" if project.version is unspecified.

[https://github.com/Transmode/gradle-docker#task-configuration-through-task-properties](url)

**Comment by dsyer** [comment]
When I run the gradle build in the "complete" sample (per the README) it creates an image with the "latest" tag. I guess your configuration was slightly different (you set a project.version).
