### ISSUE TITLE
Error: Invalid or corrupt jarfile /app.jar

### ISSUE THREAD

**Issue by ccit-spence** [spring-guides/gs-spring-boot-docker#2]
I have setup the following Dockerfile. Everything seems to build fine but getting the error that it is corrupt.  I did verify that java 8 is set in the POM and manually executed the jar so I know it is working.  The other change is that I moved the Dockerfile to the project root.  Docker complains about any type of `../` being used to get a path.  

Should this work?

    FROM dockerfile/java:oracle-java8
    VOLUME /tmp
    ADD target/core-0.1.0-RELEASE.jar app.jar
    RUN bash -c 'touch /app.jar'
    ENTRYPOINT ["java","-jar","-Dspring.profiles.active=local","/app.jar"]

**Comment by dsyer** [comment]
It depends on the pom (which you don't show). Dockerfile `ADD` works relative to the Dockerfile, so for yours to work you need to copy the jar file to a "target" directory in "target/docker". The maven plugin allows you to do that with a `<resources/>` element.

**Comment by ccit-spence** [comment]
I am actually using the IntelliJ to build the Docker Image.  So maven is not being used to build the image.  Are you saying that this is how the `ADD` should look? `ADD target/core-0.1.0-RELEASE.jar target/app.jar`

**Comment by ccit-spence** [comment]
ok, got it to work.

    FROM dockerfile/java:oracle-java8
    VOLUME /tmp
    ADD target/core-0.1.0-RELEASE.jar target/app.jar
    RUN bash -c 'touch target/app.jar'
    ENTRYPOINT ["java","-jar","-Dspring.profiles.active=local","target/app.jar"]

**Comment by ccit-spence** [comment]
Thanks for the pointer on the `target`  I am still learning Docker.  Finding it important for working with Spring Cloud at the desktop level.

**Comment by DILEEP-YADAV** [comment]
Same issue! Please help me.

![error](https://user-images.githubusercontent.com/8583769/35170469-6a1c8ea0-fd86-11e7-84a5-23159c10782e.PNG)

**Comment by DILEEP-YADAV** [comment]
I am using Gitlab CI  AutoDev tool for build docker image for spring boot app with MySQL.
a build is the success but running" docker-compose up " getting the same issue. It working fine on my local build image. Please help me.

**Comment by DILEEP-YADAV** [comment]
compose.yml
`
version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=TechlaviyaDB
      - MYSQL_PASSWORD=12345

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - docker-mysql
    environment:
      PMA_HOST: docker-mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
  docker-webapp:
    image: registry.gitlab.com/techlaviya/techlaviya/master:fb9e0213d6d4f385161e29561e626090a780e517
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=TechlaviyaDB
      - DATABASE_PORT=3306
`

**Comment by DILEEP-YADAV** [comment]
pom 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.techlaviya.lfee</groupId>
	<artifactId>techlaviya</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>techlaviya</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.8.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<start-class>com.techlaviya.lfee.TechlaviyaApplication</start-class>
		<docker.image.prefix>techlaviya</docker.image.prefix>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.4.0</version>
		</dependency>


		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.8.9</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.mobile</groupId>
			<artifactId>spring-mobile-device</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>


	</dependencies>

	<build>
		<finalName>TECHLAVIYA</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<version>1.3.6</version>
				<executions>
					<execution>
						<id>default</id>
						<goals>
							<goal>build</goal>
							<goal>push</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<repository>${docker.image.prefix}/${project.artifactId}</repository>
					<buildArgs>
						<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>
					</buildArgs>
				</configuration>


			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack</id>
						<phase>package</phase>
						<goals>
							<goal>unpack</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>${project.groupId}</groupId>
									<artifactId>${project.artifactId}</artifactId>
									<version>${project.version}</version>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>


</project>

**Comment by Floor-vds** [comment]
Did you find a solution? I have the same problem.

**Comment by givenm** [comment]
For me when I was having the issue, all I did was put the JAR_FILE in the pom without the forward slash "`/`" and it worked. 

```
<buildArgs>
           <JAR_FILE>${project.build.finalName}.jar</JAR_FILE>
</buildArgs>
```

Also my Dockerfile is like below
```

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
```

**Comment by ashish3016** [comment]
FROM ibmjava:8

MAINTAINER "ashish taware<ashish_taware@persistent.com>"

RUN mkdir -p /var/log/java-web-app

EXPOSE 8080 8081


COPY  myjar.jar /opt/aws/


WORKDIR /opt/aws/

CMD ["java", "-jar","myjar.jar"]


this is my dockerfile, it built successfully but when  i want to run executable JAR the error occurred which is  INVALID OR CURRUPT JAR file,

pls help me...

**Comment by sachinletsgo** [comment]
@ashish3016 ... I am facing the same issue. Found any solutions?

**Comment by givenm** [comment]
This is what worked for me:

```
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
MAINTAINER xxx@gmail.com
```
