### ISSUE TITLE
Change gradle plugin

### ISSUE THREAD

**Issue by geoand** [spring-guides/gs-spring-boot-docker#25]
Hello everyone,

If I were to work on a PR in which I substituted the current gradle plugin for building docker images (Transmode/gradle-docker) with [this](https://github.com/bmuschko/gradle-docker-plugin) one, is it likely it would be accepted?
The reason I believe such a change would be warranted is that the plugin used in the guide has not been updated in almost three years, while the one I propose seems to be far more active (latest release a couple months ago).

Looking forward to your feedback,
George

**Comment by gregturn** [comment]
Transmode has changed as recent as March but I get your point that it may be stale showing few changes in the past year. 

Checking out the other one, it appears to have a little of everything, which makes it unclear how well it's maintained. Have you used this for your own projects?

**Comment by geoand** [comment]
You are of course correct that Transmode has commits as late as March, it however doesn't have any releases since mid 2014.
Furthermore, besides the fact that the other project seems to have releases on regular intervals it is being also maintained by Benjamin Muschko who actually works for Gradle (for what it's worth).

I have personally used it and seems to be working quite well (except for a bug during tagging images in the latest version, but the culprit in that case is docker-java, see [this](https://github.com/bmuschko/gradle-docker-plugin/issues/364) issue)

**Comment by gregturn** [comment]
Okay sounds good. Thanks!

**Comment by geoand** [comment]
Ok, I will create a POF once I have some time :)

**Comment by dsyer** [comment]
We switched to jib.
