### ISSUE TITLE
"RUN touch app.jar" doubles size of app.jar in image

### ISSUE THREAD

**Issue by merusso** [spring-guides/gs-spring-boot-docker#27]
Can you give more details for why this is necessary? Does it still apply for newer versions of Docker? I disabled this command and didn't notice an impact -- app.jar still has a modification time.

**Comment by dsyer** [comment]
It used to be the case that the modification time was 0. Maybe that was a bug in docker and they fixed it. We used to have a bigger base image as well, so the extra layer wasn't as important.

**Comment by dsyer** [comment]
See #29
