### ISSUE TITLE
Error: Invalid or corrupt jarfile /app.jar for Gradle on Mac

### ISSUE THREAD

**Issue by cmlmonkey** [spring-guides/gs-spring-boot-docker#42]
my dockerfile :  

FROM java:8
VOLUME /tmp
ARG JAR_FILE
RUN echo ${JAR_FILE}
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

**Comment by cmlmonkey** [comment]
i echo ${JAR_FILE},there is  nothing.

**Comment by micheljung** [comment]
Hey @cmlmonkey how did you solve this issue?

**Comment by cxk1029** [comment]
@cmlmonkey do you solved thr problem

**Comment by nicatrahimov** [comment]
@cmlmonkey  do you dolved?
