### ISSUE TITLE
Accessing external data source from inside my dockerized app

### ISSUE THREAD

**Issue by ledzepu2** [spring-guides/gs-spring-boot-docker#5]
I followed the steps and created a dockerized spring boot  app which makes an external webservice call and pushes the response to redis-data store. Any pointers, what other steps i need to do enable my app to insert the data to my redis data store running in my host. I gave the ip address of the host explicitly to see if it works.

**Comment by dsyer** [comment]
Did you look for the IP address that docker assigns to your host (e.g. see here http://stackoverflow.com/questions/17770902/forward-host-port-to-docker-container)?
