### ISSUE TITLE
adoc links point to the raw format which is illegible; point to the repo instead

### ISSUE THREAD

**Issue by mub** [spring-guides/gs-spring-boot-docker#51]
The provided links to the `getting-started-macros` repo point to the raw format which is unformatted plain text. Link like this instead:

```
https://github.com/spring-guides/getting-started-macros/blob/master/prereq_editor_jdk_buildtools.adoc
```

&uarr; that would provide a [&rarr;formatted view](https://github.com/spring-guides/getting-started-macros/blob/master/prereq_editor_jdk_buildtools.adoc).

**Comment by gregturn** [comment]
Perhaps on GitHub, but not on spring.io.

**Comment by mub** [comment]
The link I proposed should work from any site.

**Comment by gregturn** [comment]
Didn't work. I tried to make that tweak, in case things had changed (https://github.com/spring-guides/gs-spring-boot-docker/commit/fdb2bddb124ab0d195e9574d45d322ce87516924).

A) The fragment is located elsewhere, hence github's security policies won't render it here, still leaving you with a link.

![screen shot 2018-06-07 at 12 07 51 pm](https://user-images.githubusercontent.com/311040/41114982-9ec96b6e-6a4b-11e8-89a1-11aef1549107.png)

B) It failed to render itself as expected.

![screen shot 2018-06-07 at 12 07 12 pm](https://user-images.githubusercontent.com/311040/41114978-9a0a0908-6a4b-11e8-82bd-96d6cb6939aa.png)

**Comment by gregturn** [comment]
So I reverted it to as it was before.

![screen shot 2018-06-07 at 12 11 04 pm](https://user-images.githubusercontent.com/311040/41115041-dfe8f4ac-6a4b-11e8-8f81-3ac2c711a802.png)
