### ISSUE TITLE
Processes In Containers Should Not Run As Root

### ISSUE THREAD

**Issue by VonUniGE** [spring-guides/gs-spring-boot-docker#56]
According to this article [Processes In Containers Should Not Run As Root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

The Dockerfile in the getting started guide should run as a user with dropped privileges.

**Comment by gregturn** [comment]
Pull requests welcome!

**Comment by VonUniGE** [comment]
Here is the PR : https://github.com/spring-guides/gs-spring-boot-docker/pull/58

**Comment by dsyer** [comment]
Closed in favour #58
