### ISSUE TITLE
Add a Docker healthcheck

### ISSUE THREAD

**Issue by jmkgreen** [spring-guides/gs-spring-boot-docker#57]
Seems reasonable to add this functionality:

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by dsyer** [comment]
Thanks for the suggestion. As I understand it a healthcheck would place requirements on the base image which we might not want or need. Most people are going to delegate health checks to a platform anyway (k8s, cloudfoundry etc.) so I'm not sure it has a huge value in a "getting started" guide.
