### ISSUE TITLE
Duplicates note

### ISSUE THREAD

**Issue by php-coder** [spring-guides/gs-spring-boot-docker#6]
In README.adoc file (and also on article http://spring.io/guides/gs/spring-boot-docker/) there is duplicated Note in "Containerize It" section:

Note: "if you are using boot2docker on a Mac you need..."
Note: "if you are using boot2docker on a Mac you need..."

**Comment by dsyer** [comment]
I think that must have been fixed already because I couldn't find it. I removed the 'on a Mac' though because it isn't strictly true. Thanks.
