### ISSUE TITLE
Process 'command 'docker'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by derekzhan** [spring-guides/gs-spring-boot-docker#65]
[root@iZm5ebsr4q0r4pplzfskpaZ complete]# ./gradlew build docker -x test

> Task :docker FAILED
flag provided but not defined: --build-arg
See 'docker build --help'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docker'.
> Process 'command 'docker'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
7 actionable tasks: 3 executed, 4 up-to-date

**Comment by dsyer** [comment]
Probably to do with dockerhub authentication. We don't use the docker plugin any more though, so I think this is obsolete.
