### ISSUE TITLE
How to achieve Key Vault feature in azure-keyvault-secrets-spring-boot by deploying in appservice as a docker image

### ISSUE THREAD

**Issue by mahammad13** [spring-guides/gs-spring-boot-docker#76]
How to achieve Key Vault feature in azure-keyvault-secrets-spring-boot by deploying in appservice as a docker image

**Comment by dsyer** [comment]
I don't think that's a relevant question for a "getting started" guide (that has nothing to do with azure). Sorry. Please try one of the Microsoft support channels.
