### ISSUE TITLE
docker --build-args vs --build-arg

### ISSUE THREAD

**Issue by soccerjoshj07** [spring-guides/gs-spring-boot-docker#77]
https://spring.io/guides/gs/spring-boot-docker/#_containerize_it

`$ docker build --build-args JAR_FILE=build/libs/*.jar -t springio/gs-spring-boot-docker .`

should be

`$ docker build --build-arg JAR_FILE=build/libs/*.jar -t springio/gs-spring-boot-docker .`

**Comment by dsyer** [comment]
Already noticed that. Fixed in da6d84ac.
