### ISSUE TITLE
Incorrect URL for Spring Guide

### ISSUE THREAD

**Issue by sankate** [spring-guides/gs-spring-boot-docker#8]
In the project description, the link to spring guide https://spring.io/guides/gs/spring-boot-docker gives a 404.

Correct URL should be https://spring.io/guides/gs/spring-boot-docker/

![image](https://cloud.githubusercontent.com/assets/1918929/7943944/c0f21ab2-091c-11e5-86fa-11a6be0cd16c.png)

**Comment by gregturn** [comment]
Fixed. Thanks!
